### ISSUE TITLE
[Error: Operation failed: BasicConsume; 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'TCP_TO_RABBIT_QUEUE_SERVER_01' in vhost '/'"]

### ISSUE THREAD

**Issue by leopucci** [typeduck/amqp-to-mongo#4]
I am getting error running this a docker conteiner. 
For some reason it does not find the queue, but the queue exists in the server 

`[Error: Operation failed: BasicConsume; 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'TCP_TO_RABBIT_QUEUE_SERVER_01' in vhost '/'"]`

 ```
rabbitmqtomongodb:
    image: marcelmaatkamp/rabbitmq-mongodb
    container_name: rabbitmqtomongodb
    restart: always
    environment:
      - AMQPHOST=amqp://admin:1111111@rabbitmq
      - MONGODB=mongodb://mongo/eeses:27018
      - MONGOCOLLECTION=gps
      - TRANSLATECONTENT=true
      - FORCECONTENTTYPE=application/json
    command: TCP_TO_RABBIT_QUEUE_SERVER_01
```

For some reason it does not work.

**Comment by typeduck** [comment]
Hi @leopucci the container itself is not from me, but I did get it to a running state such that it consumes messages from the RabbitMQ server.

Unfortunately, MongoDB has changed a lot since I wrote this, and I frankly have not kept up with the changes, so this particular configuration fails to write messages due to compatibility. I'm sure there is a MongoDB version that it _would_ work with, but the AMQP consumption works with what I've got here.

All files for setting it up are attached.
[definitions.json](https://github.com/typeduck/amqp-to-mongo/files/14398200/definitions.json)

Well, GitHub won't let me attach files with `.yml` or `.conf` extensions, so here they are as text:

rabbitmq.conf
```conf
management.load_definitions = /etc/rabbitmq/definitions.json
```

docker-compose.yml
```yaml
version: '3.8'

services:
  # RabbitMQ Server, configured to have queue defined
  rabbit:
    image: rabbitmq:3.13.0-management-alpine
    container_name: rabbit
    ports:
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
  # MongoDB Database container
  mongo:
    image: mongo:7.0.5-jammy
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # Add mongo express to administer the data
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: guest
      ME_CONFIG_BASICAUTH_PASSWORD: guest
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  # Container which ports the AMQP data into MongoDB
  amqp2mongo:
    depends_on:
      - rabbit
      - mongo
    image: marcelmaatkamp/rabbitmq-mongodb
    restart: always
    container_name: amqp2mongo
    environment:
      - AMQPHOST=amqp://guest:guest@rabbit
      - MONGODB=mongodb://root:example@mongo:27017/
      - MONGOCOLLECTION=gps
      - TRANSLATECONTENT=true
      - FORCECONTENTTYPE=application/json
    command: TCP_TO_RABBIT_QUEUE_SERVER_01
```
